#pragma once

#define WINDOW_SCREEN_WIDTH 1200
#define WINDOW_SCREEN_HEIGHT 800
#define WINDOW_SCREEN_FRAMERATE_LOW 30
#define WINDOW_SCREEN_FRAMERATE_MED 60
#define WINDOW_SCREEN_FRAMERATE_HIGH 120

#define BOARD_SIZE_X 3
#define BOARD_SIZE_Y 3
#define CELL_SIZE_X 100.f
#define CELL_SIZE_Y 100.f

#define PLAYER_SIZE_X 90.f
#define PLAYER_SIZE_Y 90.f
#define PLAYER_MARGIN_X 5.f
#define PLAYER_MARGIN_Y 5.f
